/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ProsumerRole;

import Business.Enterprise.Enterprise;
import Business.Organization.ProsumerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Pratik
 */
public class ProsumerWorkAreaPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private ProsumerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form ProsumerWorkAreaPanel
     */
    public ProsumerWorkAreaPanel(JPanel userProcessContainer, UserAccount account, ProsumerOrganization   organization, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageEnergyResources = new javax.swing.JButton();
        btnViewDataAnalytics = new javax.swing.JButton();
        javax.swing.JButton btnAutomatePowerDistribution = new javax.swing.JButton();
        javax.swing.JButton btnAmountExemptionEarned = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Prosumer Work Area");

        btnManageEnergyResources.setBackground(new java.awt.Color(0, 153, 102));
        btnManageEnergyResources.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnManageEnergyResources.setForeground(new java.awt.Color(255, 255, 255));
        btnManageEnergyResources.setText("Manage Energy Resources");
        btnManageEnergyResources.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnergyResourcesActionPerformed(evt);
            }
        });

        btnViewDataAnalytics.setBackground(new java.awt.Color(0, 153, 102));
        btnViewDataAnalytics.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnViewDataAnalytics.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDataAnalytics.setText("View Data Analytics");
        btnViewDataAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDataAnalyticsActionPerformed(evt);
            }
        });

        btnAutomatePowerDistribution.setBackground(new java.awt.Color(0, 153, 102));
        btnAutomatePowerDistribution.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAutomatePowerDistribution.setForeground(new java.awt.Color(255, 255, 255));
        btnAutomatePowerDistribution.setText("Automate Power Distribution");
        btnAutomatePowerDistribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomatePowerDistributionActionPerformed(evt);
            }
        });

        btnAmountExemptionEarned.setBackground(new java.awt.Color(0, 153, 102));
        btnAmountExemptionEarned.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAmountExemptionEarned.setForeground(new java.awt.Color(255, 255, 255));
        btnAmountExemptionEarned.setText("View Amount Exemptions");
        btnAmountExemptionEarned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmountExemptionEarnedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManageEnergyResources, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAutomatePowerDistribution, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewDataAnalytics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addComponent(btnAmountExemptionEarned, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnManageEnergyResources, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnAutomatePowerDistribution, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnAmountExemptionEarned, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnViewDataAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutomatePowerDistributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomatePowerDistributionActionPerformed
        // TODO add your handling code here:
        ProsumerAutomatePowerDistributionJPanel prosumerAutomatePowerDistribution = new ProsumerAutomatePowerDistributionJPanel(userProcessContainer, userAccount, (ProsumerOrganization)organization, enterprise);
         userProcessContainer.add("prosumerAutomatePowerDistribution", prosumerAutomatePowerDistribution);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnAutomatePowerDistributionActionPerformed

    private void btnManageEnergyResourcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnergyResourcesActionPerformed
        // TODO add your handling code here:
        
       // ProsumerManageEnergyResourcesPanel prosumerManageEnergyResources = new ProsumerManageEnergyResourcesPanel(userProcessContainer, userAccount, (ProsumerOrganization)organization, enterprise);
       ManageEnergyResoursesProsumerJPanel manageEnergyResoursesProsumer   = new ManageEnergyResoursesProsumerJPanel(userProcessContainer, userAccount, (ProsumerOrganization)organization, enterprise);
        userProcessContainer.add("manageEnergyResoursesProsumer", manageEnergyResoursesProsumer); //similar to map functions*** >> ash map*** Check*** if this is required****
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageEnergyResourcesActionPerformed

    private void btnViewDataAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDataAnalyticsActionPerformed
        // TODO add your handling code here:
        
        //ProsumerViewDataAnalyticsJPanel
        ProsumerViewDataAnalyticsJPanel prosumerViewDataAnalytics = new ProsumerViewDataAnalyticsJPanel(userProcessContainer, userAccount, (ProsumerOrganization)organization, enterprise);
         userProcessContainer.add("prosumerViewDataAnalytics", prosumerViewDataAnalytics); //similar to map functions*** >> ash map*** Check*** if this is required****
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewDataAnalyticsActionPerformed

    private void btnAmountExemptionEarnedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmountExemptionEarnedActionPerformed
        // TODO add your handling code here:
        
                
        ProsumerViewPowerExemptionJPanel prosumerViewPowerExemption = new ProsumerViewPowerExemptionJPanel(userProcessContainer, userAccount, (ProsumerOrganization)organization, enterprise);
         userProcessContainer.add("prosumerViewPowerExemption", prosumerViewPowerExemption); //similar to map functions*** >> ash map*** Check*** if this is required****
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);        
    }//GEN-LAST:event_btnAmountExemptionEarnedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageEnergyResources;
    private javax.swing.JButton btnViewDataAnalytics;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
