/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NetworkPowerControlAdmin;

import Business.EcoSystem;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import UserInterface.SystemAdminWorkAreaJPanel.ManageNetworkAdminJPanel;
import java.awt.CardLayout;
import static java.time.Clock.system;
import javax.swing.JPanel;

/**
 *
 * @author Pratik
 */
public class NetworkAdminWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Network network;
    private UserAccount userAccount;
   
    /**
     * Creates new form NetworkAdminWorkAreaJPanel
     */
    public NetworkAdminWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.userAccount=userAccount;
        

        //populateTree();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageAdminJButton = new javax.swing.JButton();
        manageEnterpriseJButton = new javax.swing.JButton();
        btnManagePower = new javax.swing.JButton();
        btnNetworkViewDataAnalyticsJPanel = new javax.swing.JButton();
        btnAutomatePowerDistribution = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("City Network Admin Work Area");

        manageAdminJButton.setBackground(new java.awt.Color(0, 153, 102));
        manageAdminJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageAdminJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageAdminJButton.setText("Manage Enterprise Admin");
        manageAdminJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdminJButtonActionPerformed(evt);
            }
        });

        manageEnterpriseJButton.setBackground(new java.awt.Color(0, 153, 102));
        manageEnterpriseJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageEnterpriseJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageEnterpriseJButton.setText("Manage Enterprise");
        manageEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseJButtonActionPerformed(evt);
            }
        });

        btnManagePower.setBackground(new java.awt.Color(0, 153, 102));
        btnManagePower.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnManagePower.setForeground(new java.awt.Color(255, 255, 255));
        btnManagePower.setText("Manage Power  From Community");
        btnManagePower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePowerActionPerformed(evt);
            }
        });

        btnNetworkViewDataAnalyticsJPanel.setBackground(new java.awt.Color(0, 153, 102));
        btnNetworkViewDataAnalyticsJPanel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNetworkViewDataAnalyticsJPanel.setForeground(new java.awt.Color(255, 255, 255));
        btnNetworkViewDataAnalyticsJPanel.setText("View Data Analytics");
        btnNetworkViewDataAnalyticsJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNetworkViewDataAnalyticsJPanelActionPerformed(evt);
            }
        });

        btnAutomatePowerDistribution.setBackground(new java.awt.Color(0, 153, 102));
        btnAutomatePowerDistribution.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAutomatePowerDistribution.setForeground(new java.awt.Color(255, 255, 255));
        btnAutomatePowerDistribution.setText("Automate Power Distribution");
        btnAutomatePowerDistribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomatePowerDistributionActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/NetworkPowerControlAdmin/CityNetwork.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNetworkViewDataAnalyticsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnManagePower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(manageAdminJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(manageEnterpriseJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAutomatePowerDistribution, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(78, 78, 78)
                .addComponent(manageEnterpriseJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(manageAdminJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnManagePower, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnAutomatePowerDistribution, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnNetworkViewDataAnalyticsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageAdminJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdminJButtonActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseAdminJPanel1 manageEnterpriseAdminJPanel = new ManageEnterpriseAdminJPanel1(userProcessContainer, network);
        userProcessContainer.add("manageEnterpriseAdminJPanel", manageEnterpriseAdminJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageAdminJButtonActionPerformed

    private void manageEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseJButtonActionPerformed

        ManageEnterpriseJPanel manageEnterpriseJPanel = new ManageEnterpriseJPanel(userProcessContainer, network);
        userProcessContainer.add("manageEnterpriseJPanel", manageEnterpriseJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseJButtonActionPerformed

    private void btnManagePowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePowerActionPerformed
        // TODO add your handling code here:
        
        ManageInputPowerJPanel manageInputPower = new ManageInputPowerJPanel(userProcessContainer,userAccount, network);
        userProcessContainer.add("manageInputPower", manageInputPower);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManagePowerActionPerformed

    private void btnNetworkViewDataAnalyticsJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNetworkViewDataAnalyticsJPanelActionPerformed
        // TODO add your handling code here:
        
        NetworkViewDataAnalyticsJPanel networkViewDataAnalytics = new NetworkViewDataAnalyticsJPanel(userProcessContainer,userAccount, network);
        userProcessContainer.add("networkViewDataAnalytics", networkViewDataAnalytics);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnNetworkViewDataAnalyticsJPanelActionPerformed

    private void btnAutomatePowerDistributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomatePowerDistributionActionPerformed
        // TODO add your handling code here:
        
        AutomatePowerDistributionJPanel automatePowerDistribution = new AutomatePowerDistributionJPanel(userProcessContainer,userAccount, network);
        userProcessContainer.add("automatePowerDistribution", automatePowerDistribution);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAutomatePowerDistributionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutomatePowerDistribution;
    private javax.swing.JButton btnManagePower;
    private javax.swing.JButton btnNetworkViewDataAnalyticsJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton manageAdminJButton;
    private javax.swing.JButton manageEnterpriseJButton;
    // End of variables declaration//GEN-END:variables
}
