/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CommunityAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
//import Business.Organization.CommunityOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Pratik
 */
public class ViewManagePowerAllocationJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    //private CommunityOrganization organization;  
    private Organization organization;
    private UserAccount userAccount;
    private EcoSystem business;
    private Network network;
    
    /**
     * Creates new form ViewManagePowerAllocationJPanel
     */
    public ViewManagePowerAllocationJPanel(JPanel userProcessContainer, UserAccount account, Organization   organization, Enterprise enterprise,Network network, EcoSystem business ) {
                //(JPanel userProcessContainer, UserAccount account, CommunityOrganization   organization, Enterprise enterprise,Network network, EcoSystem business ) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        this.network  = network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageReceivingPower = new javax.swing.JButton();
        btnManageSendingPower = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("View and Manage Power Allocation");

        btnManageReceivingPower.setBackground(new java.awt.Color(255, 255, 255));
        btnManageReceivingPower.setText("Manage Input/Receiving Power");
        btnManageReceivingPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageReceivingPowerActionPerformed(evt);
            }
        });

        btnManageSendingPower.setBackground(new java.awt.Color(255, 255, 255));
        btnManageSendingPower.setText("Manage Output/Sending Power");
        btnManageSendingPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSendingPowerActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnManageReceivingPower, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageSendingPower, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backJButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(btnManageReceivingPower)
                .addGap(28, 28, 28)
                .addComponent(btnManageSendingPower)
                .addGap(46, 46, 46)
                .addComponent(backJButton)
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageReceivingPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageReceivingPowerActionPerformed
        // TODO add your handling code here:
         ProsumerManageReceivingPowerJPanel prosumerManageReceivingPower = new ProsumerManageReceivingPowerJPanel(userProcessContainer, userAccount, organization, enterprise,network, business);
        userProcessContainer.add("prosumerManageReceivingPower", prosumerManageReceivingPower);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageReceivingPowerActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnManageSendingPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSendingPowerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageSendingPowerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnManageReceivingPower;
    private javax.swing.JButton btnManageSendingPower;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
